- name: Display environment variables
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Display value of USER variable
      shell: echo "{{ ANSIBLE_NET_USERNAME }}"

    - name: Display value of USER variable
      shell: echo "{{ ANSIBLE_NET_PASSWORD }}"
    
